#!/bin/sh

# cleanup

rm -rf obj_dir

rm -f f1_basic.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc -trace top.sv clktick.sv lfsr7.sv delay.sv f1_fsm.sv  -exe f1_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file

obj_dir/Vtop